#! /usr/bin/expect -f

set timeout -1
spawn dfrotz zmforth.z5
match_max 100000
expect "> "
send -- "load\r"
expect -re "Please enter a filename .*: "
send -- "tools.rec\r"
expect "Do you want MORE prompts? (y/n) >"
send -- "n\r"
expect "> "
send -- "load\r"
expect -re "Please enter a filename .*: "
send -- "tests.rec\r"
expect "Do you want MORE prompts? (y/n) >"
send -- "y\r"
expect "***MORE***"
send -- "\r"
expect "***MORE***"
send -- "\r"
expect -exact "\r\n  ok\r\n> "
send -- "bye\r"
expect eof
