#! /usr/bin/expect -f

set timeout -1
spawn dfrotz zmforth-base.z5
match_max 100000
expect "> "
send -- "load\r"
expect -re "Please enter a filename .*: "
send -- "zmforth.rec\r"
expect "Do you want MORE prompts? (y/n) >"
send -- "n\r"
expect -exact "n\r\n  Do you want MORE prompts? (y/n) >n\r\n  ok\r\n> "
send -- "@save\r"
expect -re "Please enter a filename .*: "
send -- "zmforth.sav\r"
expect "> "
send -- "bye\r"
expect eof
